<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.MongoDB.Driver" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChatRooms.Presentation\ChatRooms.Presentation.csproj" />
    <ProjectReference Include="..\ChatRooms.Infrastructure\ChatRooms.Infrastructure.csproj" />
    <ProjectReference Include="..\ChatRooms.ServiceDefaults\ChatRooms.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>